# Generated by Django 3.0.4 on 2020-04-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdemy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
