# Generated by Django 3.0.4 on 2020-04-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdemy_app', '0002_auto_20200403_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enroll',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
